// SVG rendering for commit graphs, matching the look of the static diagrams
// generated by book/diagrams.mjs.

const FONT = "Helvetica Neue, Helvetica, Arial, sans-serif";
const MONO = "SFMono-Regular, Menlo, Consolas, Liberation Mono, monospace";
export const BLUE = "#729fcf";
export const BLUE_DARK = "#3465a4";
export const GREEN = "#73d216";
export const GREEN_DARK = "#4e9a06";
export const ORANGE = "#fcaf3e";
export const ORANGE_DARK = "#ce5c00";
export const GREY = "#888a85";
export const INK = "#2e3436";

export const R = 26;
export const COL = 110;
export const ROW = 90;

const textWidth = (s, size, mono) => s.length * size * (mono ? 0.62 : 0.55);

function bounds(shape) {
  if (shape.kind === "circle") return { x: shape.x - R, y: shape.y - R, w: 2 * R, h: 2 * R };
  const w = textWidth(shape.text, 18, shape.mono) + 24;
  return { x: shape.x - w / 2, y: shape.y - 18, w, h: 36 };
}

const centre = (b) => ({ x: b.x + b.w / 2, y: b.y + b.h / 2 });

function boundaryPoint(shape, tx, ty) {
  const b = bounds(shape);
  const c = centre(b);
  const dx = tx - c.x;
  const dy = ty - c.y;
  if (shape.kind === "circle") {
    const len = Math.hypot(dx, dy) || 1;
    return { x: c.x + (dx / len) * R, y: c.y + (dy / len) * R };
  }
  const sx = dx === 0 ? Infinity : b.w / 2 / Math.abs(dx);
  const sy = dy === 0 ? Infinity : b.h / 2 / Math.abs(dy);
  const s = Math.min(sx, sy);
  return { x: c.x + dx * s, y: c.y + dy * s };
}

function strokeFor(fill) {
  if (fill === GREEN) return GREEN_DARK;
  if (fill === ORANGE) return ORANGE_DARK;
  return BLUE_DARK;
}

// shapes: [{ kind: "circle" | "label", id, x, y, text, mono?, ghost?, fill?, highlight? }]
// edges:  [{ from, to, ghost?, dashed? }]
export function Graph({ shapes, edges, onSelect, selected, minWidth = 0 }) {
  const byId = Object.fromEntries(shapes.map((s) => [s.id, s]));
  const all = shapes.map(bounds);
  const pad = 20;
  const minX = Math.min(...all.map((b) => b.x)) - pad;
  const minY = Math.min(...all.map((b) => b.y)) - pad;
  const maxX = Math.max(...all.map((b) => b.x + b.w)) + pad;
  const maxY = Math.max(...all.map((b) => b.y + b.h)) + pad;
  const w = Math.max(Math.round(maxX - minX), minWidth);
  const h = Math.round(maxY - minY);

  return (
    <svg viewBox={`${minX} ${minY} ${w} ${h}`} width={w} height={h} className="hg-graph" role="img">
      <defs>
        <marker id="hg-arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="8" markerHeight="8" orient="auto-start-reverse">
          <path d="M 0 0 L 10 5 L 0 10 z" fill={INK} />
        </marker>
        <marker id="hg-arrow-ghost" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="8" markerHeight="8" orient="auto-start-reverse">
          <path d="M 0 0 L 10 5 L 0 10 z" fill={GREY} />
        </marker>
      </defs>
      {edges.map((e, i) => {
        const from = byId[e.from];
        const to = byId[e.to];
        if (!from || !to) return null;
        const fc = centre(bounds(from));
        const tc = centre(bounds(to));
        const p1 = boundaryPoint(from, tc.x, tc.y);
        const p2 = boundaryPoint(to, fc.x, fc.y);
        return (
          <path
            key={i}
            d={`M ${p1.x} ${p1.y} L ${p2.x} ${p2.y}`}
            fill="none"
            stroke={e.ghost ? GREY : INK}
            strokeWidth="1.5"
            strokeDasharray={e.dashed || e.ghost ? "6 4" : undefined}
            opacity={e.ghost ? 0.5 : 1}
            markerEnd={`url(#${e.ghost ? "hg-arrow-ghost" : "hg-arrow"})`}
          />
        );
      })}
      {shapes.map((s) => {
        const b = bounds(s);
        const c = centre(b);
        const clickable = !!onSelect && s.kind === "circle";
        const common = {
          opacity: s.ghost ? 0.35 : 1,
          onClick: clickable ? () => onSelect(s.id) : undefined,
          style: clickable ? { cursor: "pointer" } : undefined,
        };
        if (s.kind === "circle") {
          const fill = s.fill ?? BLUE;
          const isSelected = selected === s.id;
          return (
            <g key={s.id} {...common}>
              {isSelected && <circle cx={c.x} cy={c.y} r={R + 6} fill="none" stroke={ORANGE_DARK} strokeWidth="3" />}
              <circle cx={c.x} cy={c.y} r={R} fill={fill} stroke={strokeFor(fill)} strokeWidth="1.5" strokeDasharray={s.ghost ? "6 4" : undefined} />
              <text x={c.x} y={c.y} textAnchor="middle" dominantBaseline="central" fontFamily={FONT} fontSize="22" fill={INK}>
                {s.text}
              </text>
            </g>
          );
        }
        return (
          <g key={s.id} {...common}>
            <rect x={b.x} y={b.y} width={b.w} height={b.h} fill="#ffffff" stroke={s.highlight ? ORANGE_DARK : BLUE_DARK} strokeWidth={s.highlight ? 3 : 1.5} strokeDasharray={s.ghost ? "6 4" : undefined} />
            <text x={c.x} y={c.y} textAnchor="middle" dominantBaseline="central" fontFamily={s.mono ? MONO : FONT} fontSize="18" fill={INK}>
              {s.text}
            </text>
          </g>
        );
      })}
    </svg>
  );
}
