on:
  push:

jobs:
  set-environment:
    runs-on: ubuntu-latest
    permissions:
      deployments: write
    steps:
      - uses: actions/checkout@v1

      - name: Start deployment
        uses: bobheadxi/deployments@v1
        id: deployment
        with:
          step: start
          token: ${{ secrets.GITHUB_TOKEN }}
          env: preview

      - name: Get Netlify URL
        uses: voorhoede/get-netlify-url@v2
        id: get-netlify-url
        with:
          site-name: structuredthoughtsblog

      - name: Update deployment status
        uses: bobheadxi/deployments@v1
        if: always()
        with:
          step: finish
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status }}
          env: ${{ steps.deployment.outputs.env }}
          env_url: ${{ steps.get-netlify-url.outputs.url }}
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
